name: auth-service-test

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: { 
    inputs: { 
      branch: { required: true, description: "Branch to test", default: "master"} 
    } 
  }

jobs:
    install-dependencies:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [18.x]
      steps:
        - uses: actions/checkout@v2
        - name: installing node dependencies
          run: 
            npm install 